chore(test): add POM page for bootc
containers/podman-desktop-extension-bootc pull request #469
Opened 2024-05-14 10:03 UTC by cbr7

### What does this PR do?
Adds POM page for bootc e2e testing.

### What issues does this PR fix or reference?
https://github.com/containers/podman-desktop-extension-bootc/issues/214

2024-05-20 14:42 UTC, odockal commented on tests/playwright/src/bootc-extension.spec.ts
> +          const bootcPAge = new BootcPage(page, webview);
just a typo.

2024-05-20 14:45 UTC, odockal requested changes

2024-05-20 14:45 UTC, odockal commented on tests/playwright/src/model/bootc-page.ts
> + * Copyright (C) 2023 Red Hat, Inc.
2024

2024-05-20 14:45 UTC, odockal commented on tests/playwright/src/model/bootc-page.ts
> +    this.rawCheckbox = webview.locator('label[for="raw"]');
looks like we could tackle ARIA functionality on the extension side? Please create an issue. Then we could use getByRole instead of locator.

2024-05-21 08:50 UTC, cbr7 commented on tests/playwright/src/model/bootc-page.ts
> + * Copyright (C) 2023 Red Hat, Inc.
fixed

2024-05-21 08:50 UTC, cbr7 commented on tests/playwright/src/bootc-extension.spec.ts
> +          const bootcPAge = new BootcPage(page, webview);
removed type.

2024-05-21 09:41 UTC, odockal approved these changes

2024-05-21 09:44 UTC, merged