feat: add launch action to bootable images
containers/podman-desktop-extension-bootc pull request #83
Opened 2024-01-24 16:29 UTC by deboer-tim

### What does this PR do?

Now that we clean up after a successful build, there's no way to launch vfkit on the image. This adds a command to bootable images, which tries to launch vfkit against the last disk image build.

### Screenshot / video of UI

<img width="938" alt="Screenshot 2024-01-24 at 11 28 00 AM" src="https://github.com/containers/podman-desktop-extension-bootc/assets/19958075/b4bcda24-a4eb-4452-b483-2ef302914256">

### What issues does this PR fix or reference?

Fixes part of #18.

### How to test this PR?

Launch the action on a bootable container that you haven't built before (it fails), then build an image and retry.

2024-01-25 19:58 UTC, cdrage requested changes
It worked!

Had no issues launching the previous image via vfkit. So all of this LGTM. Thanks for adding it to the image list instead.

Only change is we need to update the package.json as well to remove it from container page.

2024-01-25 19:58 UTC, cdrage requested changes

2024-01-25 19:58 UTC, cdrage commented on package.json
> +          "command": "bootc.vfkit",
we should also remove the previous part about it being in container page: https://github.com/containers/podman-desktop-extension-bootc/blob/b275f8ff58183aaa2c2de0fea9821f1ea070623d/package.json#L28

2024-01-26 13:55 UTC, jwboyer commented
I gave this PR a try because the build container is cleaned up too quickly so there's no opportunity to start it from that screen.  I merged it locally with #91 also included.  I built a disk image successfully and then tried to launch it and it failed.  This is the command it produced:

`main ↪️ [bootc-extension] --cpus,2,--memory,2048,--bootloader,efi,variable-store=./efi-variable-store,create,--device,virtio-blk,path=/Users/jboyer/images/jwboyer-eln,--device,virtio-serial,logFilePath=/Users/jboyer/images/vfkit-serial.log,--device,virtio-net,nat,mac=72:20:43:d4:38:62,--device,virtio-rng,--device,virtio-input,keyboard,--device,virtio-input,pointing,--device,virtio-gpu,width=1920,height=1080,--gui`

Note the virtio-blk,path specified didn't include the `...../images/disk.raw` part.

I looked at the code and it seems like we're passing the `selectedFolder` into history and not the actual image path.  I tried this diff and it at least tried to launch the VM:

```
diff --git a/src/build-disk-image.ts b/src/build-disk-image.ts
index 0854399..2a2e53b 100644
--- a/src/build-disk-image.ts
+++ b/src/build-disk-image.ts
@@ -88,7 +88,7 @@ export async function buildDiskImage(imageData: unknown, history: History) {
   }
 
   // store this path for later
-  await history.addImageBuild(image.name, selectedType, selectedFolder);
+  await history.addImageBuild(image.name, selectedType, imagePath);
 
   return extensionApi.window.withProgress(
     { location: extensionApi.ProgressLocation.TASK_WIDGET, title: 'Building disk image ' + image.name },
```

The VM doesn't actually boot, but at least the vfkit invocation is correct.

2024-01-26 14:11 UTC, jwboyer commented
FWIW, here's a screenshot of the VM after the changes mentioned above:

<img width="1173" alt="image" src="https://github.com/containers/podman-desktop-extension-bootc/assets/1058117/58ed96bf-444a-46ab-9719-acd30b4eb48c">

and the command that was run:
`main ↪️ [bootc-extension] --cpus,2,--memory,2048,--bootloader,efi,variable-store=./efi-variable-store,create,--device,virtio-blk,path=/Users/jboyer/images/jwboyer-eln/image/disk.raw,--device,virtio-serial,logFilePath=/Users/jboyer/images/jwboyer-eln/image/vfkit-serial.log,--device,virtio-net,nat,mac=72:20:43:d4:38:62,--device,virtio-rng,--device,virtio-input,keyboard,--device,virtio-input,pointing,--device,virtio-gpu,width=1920,height=1080,--gui`

Not sure if this is an issue with the disk itself, or something with vfkit

2024-01-26 14:48 UTC, cdrage commented
> FWIW, here's a screenshot of the VM after the changes mentioned above:
> 
> <img alt="image" width="1173" src="https://private-user-images.githubusercontent.com/1058117/300008336-58ed96bf-444a-46ab-9719-acd30b4eb48c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODA1NjIsIm5iZiI6MTcwNjI4MDI2MiwicGF0aCI6Ii8xMDU4MTE3LzMwMDAwODMzNi01OGVkOTZiZi00NDRhLTQ2YWItOTcxOS1hY2QzMGI0ZWI0OGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjZUMTQ0NDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzE4YjFkN2NhZWM1NDlmYWRmYzZlNDBmY2VjMTc0NjMxMDRhYjY3ZmVmMDdhNTdiYjk0MDYzMmNlMzEyNGU5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TFRdXVVe_Azpl7kXAtM0bO1t2rOu_rPYAz_t1fk_rac">
> and the command that was run: `main ↪️ [bootc-extension] --cpus,2,--memory,2048,--bootloader,efi,variable-store=./efi-variable-store,create,--device,virtio-blk,path=/Users/jboyer/images/jwboyer-eln/image/disk.raw,--device,virtio-serial,logFilePath=/Users/jboyer/images/jwboyer-eln/image/vfkit-serial.log,--device,virtio-net,nat,mac=72:20:43:d4:38:62,--device,virtio-rng,--device,virtio-input,keyboard,--device,virtio-input,pointing,--device,virtio-gpu,width=1920,height=1080,--gui`
> 
> Not sure if this is an issue with the disk itself, or something with vfkit

Press enter :)

This unfortunately is an issue with bootc-image-builder at the moment where it is getting "stuck" on the VM load: https://github.com/osbuild/bootc-image-builder/issues/105 and the screen isn't correctly refreshing.

They are at the moment working on improving the kernel parameters / templating the bootc image builder so that it would work correct.u

2024-01-26 14:54 UTC, jwboyer commented
> > Not sure if this is an issue with the disk itself, or something with vfkit
> 
> Press enter :)

I tried that before reporting 😄   Didn't do anything.

> This unfortunately is an issue with bootc-image-builder at the moment where it is getting "stuck" on the VM load: [osbuild/bootc-image-builder#105](https://github.com/osbuild/bootc-image-builder/issues/105) and the screen isn't correctly refreshing.
> 
> They are at the moment working on improving the kernel parameters / templating the bootc image builder so that it would work correctly.

OK.  I can be patient.  Thanks for the pointer.

2024-02-13 21:55 UTC, deboer-tim commented
As per comments elsewhere, we would love to provide options to test or run the disk image after building, but vfkit continued to have problems for users, and we have found no stable/open-source/compatible enough alternative. I'm finally withdrawing this PR, and we can follow up with new issues if there's another option.

2024-02-13 21:55 UTC, closed without merging